apiVersion: v1
kind: Service
metadata:
  name: xdata-admin-svc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: xdata-admin
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xdata-admin
  name: xdata-admin
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xdata-admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xdata-admin
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-a230fbde
      containers:
        - env:
            - name: PKG_RELEASE
              value: 1~buster
          image: 086115989834.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ijingzhun/xdata-admin:0.0.34
          imagePullPolicy: IfNotPresent
          name: xdata-admin
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          